# Generated by Django 2.1 on 2020-04-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='division',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='inicio_alquiler',
            field=models.DateTimeField(),
        ),
    ]
