# Generated by Django 2.1 on 2020-04-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200406_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
            preserve_default=False,
        ),
    ]
