# Generated by Django 2.1 on 2020-04-07 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_departamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
    ]
