# Generated by Django 2.1 on 2020-04-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200407_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicial', models.DateTimeField()),
                ('dia_final', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='fin_alquiler',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='inicio_alquiler',
        ),
        migrations.AddField(
            model_name='reserva',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Departamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Reserva'),
            preserve_default=False,
        ),
    ]
