# Generated by Django 2.1 on 2020-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200408_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia_final',
            field=models.DateTimeField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia_inicial',
            field=models.DateTimeField(unique_for_date=True),
        ),
    ]
