# Generated by Django 2.1 on 2020-04-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200409_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia_final',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia_inicial',
            field=models.DateTimeField(unique=True),
        ),
    ]
