# Generated by Django 2.1 on 2020-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200409_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia_inicial',
            field=models.DateField(),
        ),
    ]
