# Generated by Django 2.1 on 2020-04-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200410_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='reserva',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
