# Generated by Django 2.1 on 2020-04-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200410_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicial', models.DateField()),
                ('dia_final', models.DateField()),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Reserva'),
            preserve_default=False,
        ),
    ]
